groups:
  - name: hive-mind-alerts
    interval: 30s
    rules:
      # High-level service availability
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute"
          runbook_url: "https://docs.hive-mind.ai/runbooks/service-down"

      # Claude-TUI specific alerts
      - alert: ClaudeTUIHighErrorRate
        expr: rate(claude_tui_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: claude-tui
        annotations:
          summary: "High error rate in Claude-TUI"
          description: "Claude-TUI error rate is {{ $value }} errors per second"

      - alert: ClaudeTUIHighLatency
        expr: histogram_quantile(0.95, rate(claude_tui_http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: claude-tui
        annotations:
          summary: "High latency in Claude-TUI"
          description: "95th percentile latency is {{ $value }}s"

      # Memory and CPU alerts
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85%"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80%"

      # Database alerts
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High number of PostgreSQL connections"
          description: "{{ $value }} connections are active"

      # Hive Mind specific alerts
      - alert: HiveMindCoordinatorDown
        expr: up{job="hive-mind-coordinator"} == 0
        for: 30s
        labels:
          severity: critical
          component: hive-mind
        annotations:
          summary: "Hive Mind Coordinator is down"
          description: "The central coordination service is not responding"

      - alert: SwarmAgentFailureRate
        expr: rate(hive_mind_agent_failures_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          component: hive-mind
        annotations:
          summary: "High swarm agent failure rate"
          description: "Agent failure rate is {{ $value }} failures per second"

      - alert: MCPServerUnresponsive
        expr: up{job="mcp-server"} == 0
        for: 1m
        labels:
          severity: critical
          component: integration
        annotations:
          summary: "MCP Server is unresponsive"
          description: "Model Context Protocol server is down"

      # Performance alerts
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.90
        for: 5m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "High disk usage on {{ $labels.instance }}"
          description: "Disk usage is above 90% on mount {{ $labels.mountpoint }}"

      - alert: NetworkHighTraffic
        expr: rate(node_network_receive_bytes_total[5m]) > 100000000  # 100MB/s
        for: 5m
        labels:
          severity: warning
          component: network
        annotations:
          summary: "High network traffic"
          description: "Network receive rate is {{ $value }} bytes/second"

      # Security alerts
      - alert: SecurityAuditFailures
        expr: rate(security_audit_failures_total[5m]) > 0.01
        for: 1m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "Security audit failures detected"
          description: "{{ $value }} security failures per second"

      - alert: UnauthorizedAccessAttempts
        expr: rate(auth_failed_attempts_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "{{ $value }} failed auth attempts per second"

      # Application-specific SLO alerts
      - alert: SLOThroughputViolation
        expr: rate(claude_tui_http_requests_total[5m]) < 10
        for: 10m
        labels:
          severity: warning
          slo: throughput
        annotations:
          summary: "SLO violation: Low throughput"
          description: "Request rate is {{ $value }} req/s, below SLO threshold"

      - alert: SLOAvailabilityViolation
        expr: (rate(claude_tui_http_requests_total{status!~"5.."}[5m]) / rate(claude_tui_http_requests_total[5m])) < 0.999
        for: 5m
        labels:
          severity: critical
          slo: availability
        annotations:
          summary: "SLO violation: Low availability"
          description: "Service availability is {{ $value }}, below 99.9% SLO"

      # Claude Flow integration alerts
      - alert: ClaudeFlowIntegrationDown
        expr: up{job="claude-flow"} == 0
        for: 2m
        labels:
          severity: warning
          component: integration
        annotations:
          summary: "Claude Flow integration is down"
          description: "Claude Flow service is not responding"

      - alert: NeuralModelLatency
        expr: histogram_quantile(0.95, rate(neural_model_inference_duration_seconds_bucket[5m])) > 5
        for: 3m
        labels:
          severity: warning
          component: ai
        annotations:
          summary: "High neural model inference latency"
          description: "95th percentile inference time is {{ $value }}s"