apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: claude-tui-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: claude-tui
    app.kubernetes.io/component: monitoring
spec:
  groups:
  - name: claude-tui.availability
    rules:
    - alert: ClaudeTUIDown
      expr: up{job="claude-tui"} == 0
      for: 1m
      labels:
        severity: critical
        service: claude-tui
      annotations:
        summary: "Claude-TUI service is down"
        description: "Claude-TUI service has been down for more than 1 minute."
        
    - alert: ClaudeTUIHighErrorRate
      expr: rate(claude_tui_http_requests_total{status=~"5.."}[5m]) / rate(claude_tui_http_requests_total[5m]) * 100 > 5
      for: 2m
      labels:
        severity: critical
        service: claude-tui
      annotations:
        summary: "High error rate detected"
        description: "Claude-TUI error rate is {{ $value }}% for more than 2 minutes."
        
    - alert: ClaudeTUISlowResponse
      expr: histogram_quantile(0.95, rate(claude_tui_http_request_duration_seconds_bucket[5m])) > 0.5
      for: 3m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "Slow response times detected"
        description: "95th percentile response time is {{ $value }}s for more than 3 minutes."

  - name: claude-tui.resources
    rules:
    - alert: ClaudeTUIHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"claude-tui-.*"} / container_spec_memory_limit_bytes * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "High memory usage"
        description: "Pod {{ $labels.pod }} memory usage is {{ $value }}% of limit."
        
    - alert: ClaudeTUIHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"claude-tui-.*"}[5m]) * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "High CPU usage"
        description: "Pod {{ $labels.pod }} CPU usage is {{ $value }}%."
        
    - alert: ClaudeTUIMemoryLeak
      expr: increase(container_memory_usage_bytes{pod=~"claude-tui-.*"}[1h]) > 50000000
      for: 0m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "Potential memory leak detected"
        description: "Pod {{ $labels.pod }} memory increased by {{ $value | humanize }}B in the last hour."

  - name: claude-tui.scaling
    rules:
    - alert: ClaudeTUIPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"claude-tui-.*"}[15m]) > 0
      for: 0m
      labels:
        severity: critical
        service: claude-tui
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently."
        
    - alert: ClaudeTUIDeploymentReplicasMismatch
      expr: kube_deployment_spec_replicas{deployment="claude-tui-app"} != kube_deployment_status_replicas_available{deployment="claude-tui-app"}
      for: 5m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "Deployment replicas mismatch"
        description: "Deployment {{ $labels.deployment }} has {{ $value }} available replicas, expected {{ $labels.replicas_desired }}."
        
    - alert: ClaudeTUIHPAMaxReplicasReached
      expr: kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler="claude-tui-hpa"} >= kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler="claude-tui-hpa"}
      for: 10m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "HPA at maximum replicas"
        description: "HPA has reached maximum replicas ({{ $value }}). Consider increasing limits."

  - name: claude-tui.business
    rules:
    - alert: ClaudeTUILowThroughput
      expr: rate(claude_tui_requests_total[5m]) < 10
      for: 10m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "Low request throughput"
        description: "Claude-TUI is processing only {{ $value }} requests/second."
        
    - alert: ClaudeTUIAIServiceDown
      expr: claude_tui_ai_service_up == 0
      for: 1m
      labels:
        severity: critical
        service: claude-tui
      annotations:
        summary: "AI service unavailable"
        description: "Claude AI service is not responding."
        
    - alert: ClaudeTUISwarmCoordinationFailure
      expr: claude_tui_swarm_coordination_errors_total > 0
      for: 2m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "Swarm coordination failures"
        description: "{{ $value }} swarm coordination errors detected."

  - name: claude-tui.infrastructure
    rules:
    - alert: ClaudeTUIPersistentVolumeUsage
      expr: kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"claude-tui-.*"} / kubelet_volume_stats_capacity_bytes * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: claude-tui
      annotations:
        summary: "High persistent volume usage"
        description: "PVC {{ $labels.persistentvolumeclaim }} is {{ $value }}% full."
        
    - alert: ClaudeTUIDatabaseConnectionFailure
      expr: claude_tui_database_connections_active / claude_tui_database_connections_max * 100 > 90
      for: 2m
      labels:
        severity: critical
        service: claude-tui
      annotations:
        summary: "Database connection pool exhausted"
        description: "Database connection usage is {{ $value }}% of maximum."