apiVersion: v1
kind: Namespace
metadata:
  name: claude-tui
  labels:
    name: claude-tui
    app.kubernetes.io/name: claude-tui
    app.kubernetes.io/part-of: claude-tui-platform

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: claude-tui-quota
  namespace: claude-tui
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claude-tui-network-policy
  namespace: claude-tui
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: claude-tui
    - namespaceSelector:
        matchLabels:
          name: kube-system
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: claude-tui
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80