apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: claude-tui-storage
  labels:
    app: claude-tui
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-tui-pvc
  namespace: claude-tui
  labels:
    app: claude-tui
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: claude-tui-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-tui-logs-pvc
  namespace: claude-tui
  labels:
    app: claude-tui
    type: logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: claude-tui-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-tui-backup-pvc
  namespace: claude-tui
  labels:
    app: claude-tui
    type: backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: claude-tui-storage