global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@hive-mind.ai'
  smtp_auth_username: 'alerts@hive-mind.ai'
  smtp_auth_password: '${SMTP_PASSWORD}'
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
      continue: true

    # Warning alerts go to Slack
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

    # Security alerts have special routing
    - match:
        component: security
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 10m
      continue: true

    # Database alerts
    - match:
        component: database
      receiver: 'database-team'
      group_wait: 15s
      repeat_interval: 15m

    # Hive Mind specific alerts
    - match:
        component: hive-mind
      receiver: 'hive-mind-team'
      group_wait: 10s
      repeat_interval: 10m

    # SLO violations
    - match_re:
        slo: '.*'
      receiver: 'slo-alerts'
      group_wait: 5s
      repeat_interval: 5m

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@hive-mind.ai'
        subject: 'Hive Mind Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}
            {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        details:
          alertname: '{{ .GroupLabels.alertname }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service | default "unknown" }}
          *Runbook:* {{ .Annotations.runbook_url | default "Not available" }}
          {{ end }}
        color: 'danger'

  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service | default "unknown" }}
          {{ end }}
        color: 'warning'

  - name: 'security-team'
    email_configs:
      - to: 'security@hive-mind.ai'
        subject: '🛡️ SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          SECURITY INCIDENT DETECTED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          Labels: {{ range .Labels.SortedPairs }}
            {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🛡️ SECURITY: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *SECURITY INCIDENT:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Immediate Action Required*
          {{ end }}
        color: '#ff0000'

  - name: 'database-team'
    email_configs:
      - to: 'dba@hive-mind.ai'
        subject: '🗄️ DATABASE ALERT: {{ .GroupLabels.alertname }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: '🗄️ DATABASE: {{ .GroupLabels.alertname }}'
        color: '#ff9900'

  - name: 'hive-mind-team'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#hive-mind-alerts'
        title: '🧠 HIVE MIND: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Hive Mind Alert:* {{ .Annotations.summary }}
          *Component:* {{ .Labels.component }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: '#9933ff'

  - name: 'slo-alerts'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_SLO_KEY}'
        description: 'SLO Violation: {{ .CommonAnnotations.summary }}'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#slo-violations'
        title: '📊 SLO VIOLATION: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *SLO Violation:* {{ .Annotations.summary }}
          *SLO Type:* {{ .Labels.slo }}
          *Description:* {{ .Annotations.description }}
          *Action Required:* Investigate immediately
          {{ end }}
        color: '#ff6600'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*High.*'
    equal: ['instance']