apiVersion: v1
kind: Service
metadata:
  name: claude-tui-service
  namespace: staging
  labels:
    app: claude-tui
    environment: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: claude-tui
    environment: staging
---
apiVersion: v1
kind: Service
metadata:
  name: claude-tui-internal
  namespace: staging
  labels:
    app: claude-tui
    environment: staging
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: claude-tui
    environment: staging