apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: monitoring
data:
  jaeger.yaml: |
    # Jaeger configuration for production deployment
    query:
      base-path: /jaeger
      static_files: /go/jaeger-ui-build/build
      
    collector:
      zipkin:
        host-port: ":9411"
      
    storage:
      type: elasticsearch
      options:
        es.server-urls: http://elasticsearch:9200
        es.num-shards: 5
        es.num-replicas: 1
        es.timeout: 20s
        es.sniffer: false
        es.max-doc-count: 10000
        es.max-span-age: 72h
        es.index-prefix: jaeger
        
    processor:
      jaeger-compact:
        server-host-port: 0.0.0.0:14271
        workers: 50
      jaeger-binary:
        server-host-port: 0.0.0.0:14269
        workers: 50

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/component: all-in-one
  template:
    metadata:
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.35.0
        args:
          - --memory.max-traces=50000
          - --query.base-path=/jaeger
          - --prometheus.server-url=http://prometheus:9090
          - --prometheus.query.support-spanmetrics-connector=true
        ports:
        - containerPort: 16686
          name: query
        - containerPort: 14268
          name: collector
        - containerPort: 14250
          name: grpc
        - containerPort: 6831
          name: jaeger-compact
          protocol: UDP
        - containerPort: 6832
          name: jaeger-binary
          protocol: UDP
        - containerPort: 5775
          name: zipkin-compact
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 9411
          name: zipkin
        - containerPort: 16687
          name: admin
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: METRICS_STORAGE_TYPE
          value: prometheus
        - name: PROMETHEUS_SERVER_URL
          value: "http://prometheus:9090"
        - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
          value: "true"
        - name: SPAN_STORAGE_TYPE
          value: badger
        - name: BADGER_EPHEMERAL
          value: "false"
        - name: BADGER_DIRECTORY_VALUE
          value: "/badger/data"
        - name: BADGER_DIRECTORY_KEY
          value: "/badger/key"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: badger-data
          mountPath: /badger
        livenessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 16687
          initialDelaySeconds: 10
      volumes:
      - name: badger-data
        persistentVolumeClaim:
          claimName: jaeger-badger-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
spec:
  ports:
  - name: query-http
    port: 16686
    targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: collector
spec:
  ports:
  - name: jaeger-collector-http
    port: 14268
    targetPort: 14268
  - name: jaeger-collector-grpc
    port: 14250
    targetPort: 14250
  - name: jaeger-collector-zipkin
    port: 9411
    targetPort: 9411
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: agent
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: agent-compact
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: agent-binary
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: agent-configs
    port: 5778
    targetPort: 5778
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi