groups:
  - name: claude-tui-application
    interval: 30s
    rules:
      # Application Health Alerts
      - alert: ClaudeTiuDown
        expr: up{job="claude-tui-app"} == 0
        for: 2m
        labels:
          severity: critical
          service: claude-tui
          category: availability
        annotations:
          summary: "Claude TUI application is down"
          description: "Claude TUI application on {{ $labels.instance }} has been down for more than 2 minutes."
          runbook_url: "https://github.com/claude-tui/claude-tui/wiki/Runbooks#application-down"

      - alert: ClaudeTiuHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="claude-tui-app"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: performance
        annotations:
          summary: "High latency detected in Claude TUI"
          description: "95th percentile latency is {{ $value }}s on {{ $labels.instance }}"
          runbook_url: "https://github.com/claude-tui/claude-tui/wiki/Runbooks#high-latency"

      - alert: ClaudeTiuHighErrorRate
        expr: rate(http_requests_total{job="claude-tui-app",status=~"5.."}[5m]) / rate(http_requests_total{job="claude-tui-app"}[5m]) > 0.1
        for: 3m
        labels:
          severity: critical
          service: claude-tui
          category: errors
        annotations:
          summary: "High error rate in Claude TUI"
          description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://github.com/claude-tui/claude-tui/wiki/Runbooks#high-error-rate"

      # Resource Utilization Alerts
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="claude-tui-app"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: resources
        annotations:
          summary: "High CPU usage in Claude TUI"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes{job="claude-tui-app"} / 1024 / 1024 / 1024) > 2
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: resources
        annotations:
          summary: "High memory usage in Claude TUI"
          description: "Memory usage is {{ $value }}GB on {{ $labels.instance }}"

      - alert: FileDescriptorUsage
        expr: process_open_fds{job="claude-tui-app"} / process_max_fds{job="claude-tui-app"} > 0.8
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: resources
        annotations:
          summary: "High file descriptor usage"
          description: "File descriptor usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

  - name: claude-tui-database
    interval: 30s
    rules:
      # Database Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
          category: availability
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"
          runbook_url: "https://github.com/claude-tui/claude-tui/wiki/Runbooks#database-down"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends{job="postgres-exporter"} / pg_settings_max_connections{job="postgres-exporter"} > 0.8
        for: 5m
        labels:
          severity: warning
          service: postgresql
          category: resources
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "Connection usage is {{ $value | humanizePercentage }}"

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_tup_fetched{job="postgres-exporter"}[5m]) / rate(pg_stat_database_tup_returned{job="postgres-exporter"}[5m]) > 100
        for: 5m
        labels:
          severity: warning
          service: postgresql
          category: performance
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Slow query ratio is high"

  - name: claude-tui-redis
    interval: 30s
    rules:
      # Redis Alerts
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
          category: availability
        annotations:
          summary: "Redis is down"
          description: "Redis cache is not responding"
          runbook_url: "https://github.com/claude-tui/claude-tui/wiki/Runbooks#redis-down"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes{job="redis-exporter"} / redis_memory_max_bytes{job="redis-exporter"} > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
          category: resources
        annotations:
          summary: "Redis high memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: RedisConnectionsSpike
        expr: increase(redis_connected_clients{job="redis-exporter"}[5m]) > 100
        for: 2m
        labels:
          severity: warning
          service: redis
          category: performance
        annotations:
          summary: "Redis connections spike"
          description: "Connections increased by {{ $value }} in 5 minutes"

  - name: claude-tui-security
    interval: 60s
    rules:
      # Security Alerts
      - alert: SuspiciousRequestPattern
        expr: rate(http_requests_total{job="claude-tui-app",status=~"4.."}[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: security
        annotations:
          summary: "Suspicious request pattern detected"
          description: "High rate of 4xx responses: {{ $value }}/s on {{ $labels.instance }}"

      - alert: FailedAuthenticationAttempts
        expr: rate(claude_tui_auth_failures_total{job="claude-tui-app"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: claude-tui
          category: security
        annotations:
          summary: "High rate of failed authentication attempts"
          description: "{{ $value }} failed auth attempts per second on {{ $labels.instance }}"

  - name: claude-tui-business
    interval: 60s
    rules:
      # Business Logic Alerts
      - alert: AIServiceTimeout
        expr: rate(claude_tui_ai_requests_timeout_total{job="claude-tui-app"}[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: claude-tui
          category: business
        annotations:
          summary: "AI service timeouts detected"
          description: "{{ $value }} AI requests timing out per second"

      - alert: ProjectCreationFailures
        expr: rate(claude_tui_project_creation_failures_total{job="claude-tui-app"}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: claude-tui
          category: business
        annotations:
          summary: "Project creation failures"
          description: "{{ $value }} project creation failures per second"

  - name: claude-tui-system
    interval: 30s
    rules:
      # System-level Alerts
      - alert: HighSystemLoad
        expr: node_load1{job="node-exporter"} / count(node_cpu_seconds_total{job="node-exporter",mode="idle"}) by (instance) > 0.8
        for: 5m
        labels:
          severity: warning
          service: system
          category: resources
        annotations:
          summary: "High system load"
          description: "System load is {{ $value }} on {{ $labels.instance }}"

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes{job="node-exporter",fstype!="tmpfs"} - node_filesystem_free_bytes{job="node-exporter",fstype!="tmpfs"}) / node_filesystem_size_bytes{job="node-exporter",fstype!="tmpfs"} > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
          category: resources
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: SystemOutOfMemory
        expr: (node_memory_MemTotal_bytes{job="node-exporter"} - node_memory_MemAvailable_bytes{job="node-exporter"}) / node_memory_MemTotal_bytes{job="node-exporter"} > 0.9
        for: 2m
        labels:
          severity: critical
          service: system
          category: resources
        annotations:
          summary: "System out of memory"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
