# Prometheus Configuration for Claude TUI Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'claude-tui-monitor'
    cluster: 'development'

# Alertmanager Configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules for Alerting
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape Configurations
scrape_configs:
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics

  # Claude TUI Application Metrics
  - job_name: 'claude-tui'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['claude-tui:8000']
    scrape_timeout: 10s
    honor_labels: true

  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Cache Metrics  
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node/Container Metrics
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx Metrics
  - job_name: 'nginx'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Docker Container Metrics
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  # Custom Application Metrics
  - job_name: 'claude-tui-custom'
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['claude-tui:8000']
    params:
      format: ['prometheus']

# Remote Write Configuration (for external monitoring)
# remote_write:
#   - url: "https://your-remote-prometheus/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"